version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SteliosTest"
s3_bucket = "stelios-state"
s3_prefix = "sam/SteliosTest"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
